[Bug] Switch pip camera button accessibility
Azure/communication-ui-library-android pull request #262
Opened 2022-05-18 19:20 UTC by ShaunaSong

## Purpose

* Announce the front/ back camera when user tap on the pip camera image button

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

- Turn on the Talkback
- Navigate to call setup page.
- Navigate to Join call and activate it.
- Turn Video ON
- Navigate to PIP of local video.
- Get focus on 'Switch camera button'  and activate it.
- Observe the issue.

## What to Check
Verify that the following are valid
* Talkback announce the front/ back camera

## Other Information

2022-05-18 20:28 UTC, dhiraj requested changes

2022-05-19 16:23 UTC, ShaunaSong commented on azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AccessibilityAnnouncementManager.kt
> +            else -> ""
Current logic: 
if it is FRONT, and the talkback will announce "Switch to Back Camera button, double click to activate"
If it is BACK,  and will announce "Switch to Front Camera button, double click to activate"

I think it is also make sense.

2022-05-19 16:37 UTC, lpx1989 reviewed
Tested

2022-05-19 17:01 UTC, dhiraj commented on azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AccessibilityAnnouncementManager.kt
> +            else -> ""
No, I meant when you're already on focus on the camera button, and you double tap then the announcement sounds like it is opposite. For example, say you're focused on the camera button, and the currently selected camera is front, when you double tap the button, it switches to the back camera, but the announcement is "Switch to front camera".

2022-05-20 16:52 UTC, ShaunaSong commented on azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AccessibilityAnnouncementManager.kt
> +            else -> ""
Get it. Make sense. Also check with Mic on/off logic, will follow the same logic. 

Thanks for helping.

2022-05-20 17:28 UTC, dhiraj approved these changes
Tested, looks good to me 👍

2022-05-20 17:41 UTC, lpx1989 approved these changes

2022-05-20 17:42 UTC, merged