[Bug] Support RTL for DrawerDialog
Azure/communication-ui-library-android pull request #302
Opened 2022-06-01 20:30 UTC by ShaunaSong

## Purpose

* Support RTL for Drawer Dialog

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Open setting page
* Click on isRTL checkbox

## What to Check
Verify that the following are valid
* All the UIs are Right to Left

## Other Information

|After AudioList|After ParticipantListView|After  LeaveCall|
|---|---|---|
|<img width="374" alt="Screen Shot 2022-06-02 at 9 50 33 AM" src="https://user-images.githubusercontent.com/93549644/171683257-6c0830a1-6fc3-43f8-9829-7eb00db2d8fa.png">|<img width="366" alt="Screen Shot 2022-06-02 at 9 52 27 AM" src="https://user-images.githubusercontent.com/93549644/171683305-3230f100-5c96-404f-8f2e-a9d1776201ed.png">|<img width="370" alt="Screen Shot 2022-06-02 at 9 52 37 AM" src="https://user-images.githubusercontent.com/93549644/171683340-9065ad51-2aa1-4c27-bc72-d32f1161aa78.png">|

2022-06-01 22:18 UTC, iaulakh requested changes
@ShaunaSong can we also do for leave call?
![Screen Shot 2022-06-01 at 3 18 11 PM](https://user-images.githubusercontent.com/73618019/171511092-76aed526-a9b6-4ef9-a891-3ac7e7907f6b.png)

2022-06-02 06:30 UTC, lpx1989 submitted a review, later dismissed

2022-06-02 16:54 UTC, ShaunaSong commented
> @ShaunaSong can we also do for leave call? ![Screen Shot 2022-06-01 at 3 18 11 PM](https://user-images.githubusercontent.com/73618019/171511092-76aed526-a9b6-4ef9-a891-3ac7e7907f6b.png)

Updated, please double check

2022-06-02 17:22 UTC, iaulakh approved these changes

2022-06-02 17:26 UTC, Mohtasim approved these changes

2022-06-02 17:28 UTC, merged