[Documentation] update documentation as per API changes
Azure/communication-ui-library-android pull request #326
Opened 2022-06-09 21:06 UTC by iaulakh

## Purpose

* update documentation

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

2022-06-09 21:43 UTC, ahammer approved these changes, later dismissed

2022-06-09 22:39 UTC, Mrayyan approved these changes, later dismissed

2022-06-09 23:35 UTC, Mohtasim approved these changes, later dismissed

2022-06-09 23:55 UTC, phileo99 requested changes

2022-06-09 23:55 UTC, phileo99 commented on docs/CHANGELOG_UI_CALLING.md
> +- CallComposite.launch funcions are refactored. Argument classes GroupCallOptions, TeamsMeetingOptions are removed. New argument classes are added: CallCompositeRemoteOptions, CallCompositeLocalOptio
Spelling mistake:  should be "functions"

2022-06-09 23:57 UTC, phileo99 commented on docs/CHANGELOG_UI_CALLING.md
> +- CallComposite.launch funcions are refactored. Argument classes GroupCallOptions, TeamsMeetingOptions are removed. New argument classes are added: CallCompositeRemoteOptions, CallCompositeLocalOptio
also should be `launch()`

2022-06-09 23:57 UTC, phileo99 commented
Also @iaulakh  can we trying adding the tags for code:
https://www.markdownguide.org/cheat-sheet#:~:text=Extended%20Syntax%20%20%20%20Element%20%20,sentence%20with%20a%20footnote.%207%20more%20rows%20

2022-06-09 23:58 UTC, ahammer approved these changes, later dismissed

2022-06-10 00:05 UTC, ahammer approved these changes

2022-06-10 00:06 UTC, phileo99 approved these changes
👍

2022-06-10 00:08 UTC, merged