Feature/launch chat screen
Azure/communication-ui-library-android pull request #405
Opened 2022-09-01 17:06 UTC by Mrayyan

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-09-01 17:35 UTC, iaulakh commented
@Mrayyan  may you please change this PR to :

Only having main Activity that can show button:
No change for demo app
No theming or styling
Just minimal to launch activity with a sample text like "hello"

2022-09-01 19:36 UTC, pavelprystinka requested changes

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ui/theme/Theme.kt
> +fun AzurecommunicationuiTheme(
Should AzurecommunicationuiTheme be internal?

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ui/theme/Type.kt
> +val Typography = Typography(
Please make it internal

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/res/values/themes.xml
> +    <style name="Theme.Azurecommunicationui" parent="android:Theme.Material.Light.NoActionBar">
For Calling theme name is "AzureCommunicationUICalling.Theme"
We should use same format for Chat composite as well

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/res/values/strings.xml
> +    <string name="title_activity_chat">ChatActivity</string>
All resource should start with library name prefix: azure_communication_ui_chat_

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ui/theme/Shape.kt
> +val Shapes = Shapes(
Please make it internal

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ui/theme/Color.kt
> +val Purple200 = Color(0xFFBB86FC)
Please make it internal

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatActivity.kt
> +class ChatActivity : ComponentActivity() {
Please make it internal

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatActivity.kt
> +fun Greeting(name: String) {
Please make it internal

2022-09-01 19:36 UTC, pavelprystinka commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatActivity.kt
> +fun DefaultPreview() {
Please make it internal

2022-09-07 17:29 UTC, closed without merging

2022-09-07 17:29 UTC, iaulakh commented
Closing as per discussion not required