[Refactor] Refactor Confirm Leave Overlay View logic
Azure/communication-ui-library-android pull request #5
Opened 2021-12-14 23:21 UTC by ShaunaSong

## Purpose

* Refactor confirm leave overlay logic into ViewModel

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

1. Join the Group Call/ Teams Meeting
2. Press the Hang Up Button
3. Check Confirm Leave Overlay Behaviour

## What to Check
Verify that the following are valid
* Confirm Leave Overlay Behaviour does not Change

2021-12-15 21:39 UTC, iaulakh approved these changes
tested

2021-12-15 23:46 UTC, phileo99 requested changes

2021-12-15 23:46 UTC, phileo99 commented on azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/ConfirmLeaveOverlayViewModel.kt
> +    private var shouldDisplayConfirmLeaveOverlayStateFlow = MutableStateFlow(false)
can we change this to val

2021-12-16 00:42 UTC, ShaunaSong commented on azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/ConfirmLeaveOverlayViewModel.kt
> +    private var shouldDisplayConfirmLeaveOverlayStateFlow = MutableStateFlow(false)
Updated, thanks

2021-12-16 00:43 UTC, iaulakh approved these changes

2021-12-16 01:08 UTC, phileo99 submitted a review, later dismissed
👍

2021-12-16 03:20 UTC, pavelprystinka requested changes

2021-12-16 03:20 UTC, pavelprystinka commented on azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingFragment.kt
> +        viewModel.getConfirmLeaveOverlayViewModel().show()
How about we will create a method CallingViewModel.requestCallEnd() and rename  ConfirmLeaveOverlayViewModel.show() to ConfirmLeaveOverlayViewModel.requestExitConfirmation()

Then from here: CallingFragment.requestCallEnd() call viewModel.requestCallEnd() which will call confirmLeaveOverlayViewModel.requestExitConfirmation()

2021-12-16 20:40 UTC, pavelprystinka approved these changes

2021-12-16 22:00 UTC, iaulakh approved these changes

2021-12-16 22:04 UTC, merged