[Chat][Feature] Match Typing Indicator UI with Figma
Azure/communication-ui-library-android pull request #530
Opened 2022-10-19 23:29 UTC by v-loalbert

## Purpose

* Match Typing Indicator UI with Figma

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-10-19 23:50 UTC, ahammer commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/chat/screens/ChatScreen.kt
> +                Spacer(modifier = Modifier.height(20.dp))
can this be padding inside TypingIndicatorView via a modifier.

When the Indicator isn't visible, we probably don't want the padding?

2022-10-19 23:51 UTC, ahammer requested changes
Visible when nothing there.

Shows over list as a white box.

Needs visibility logic or AnimatedVisibility container.

2022-10-20 00:47 UTC, ahammer approved these changes, later dismissed

2022-10-20 01:57 UTC, iaulakh requested changes
please use xml strings

2022-10-20 16:42 UTC, ahammer submitted a review, later dismissed

2022-10-20 17:22 UTC, iaulakh approved these changes

2022-10-20 17:37 UTC, ShaunaSong approved these changes

2022-10-20 17:38 UTC, merged