[Chat][feature] Participants list
Azure/communication-ui-library-android pull request #539
Opened 2022-10-23 22:53 UTC by dhiraj

## Purpose

* Displays participants list on click of participants count and returns back to messages list on tapping again on the count button or the back button

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Join a chat thread that has participants
* Tap on the participants count to show/hide the participants

## What to Check
Verify that the following are valid
* All the participants are showing as per count
* Appear / Dismiss of participants list works as expected
* Visual layout and alignment of composable works as expected

2022-10-24 16:32 UTC, iaulakh commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/chat/components/ParticipantsListView.kt
> +internal fun ParticipantsListView(
@dhiraj can we use Fluent UI list controls?

2022-10-24 16:32 UTC, iaulakh requested changes
Detected crash on screen rotate:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azure.android.communication.ui.callingcompositedemoapp.debug, PID: 17358
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.azure.android.communication.ui.callingcompositedemoapp.debug/com.azure.android.communication.ui.chat.presentation.ChatCompositeActivity}: java.lang.IllegalArgumentException: Builder for class com.azure.android.communication.ui.chat.ChatComposite Does not exist
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6347)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: Builder for class com.azure.android.communication.ui.chat.ChatComposite Does not exist
        at com.azure.android.communication.ui.chat.presentation.ChatCompositeActivity$chatComposite$2.invoke(ChatCompositeActivity.kt:40)
        at com.azure.android.communication.ui.chat.presentation.ChatCompositeActivity$chatComposite$2.invoke(ChatCompositeActivity.kt:15)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.azure.android.communication.ui.chat.presentation.ChatCompositeActivity.getChatComposite(ChatCompositeActivity.kt:15)
        at com.azure.android.communication.ui.chat.presentation.ChatCompositeActivity.onCreate(ChatCompositeActivity.kt:22)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8270)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6347) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
I/Process: Sending signal. PID: 17358 SIG: 9

2022-10-24 19:59 UTC, iaulakh commented
@dhiraj Fima shows people as header when list opens:
![Screen Shot 2022-10-24 at 12 58 19 PM](https://user-images.githubusercontent.com/73618019/197617335-5d521313-3272-4874-b04a-9f26e8c4b087.png)

2022-10-25 17:08 UTC, ahammer submitted a review, later dismissed

2022-10-25 23:25 UTC, dhiraj commented
Now using FluentUI controls to render the participants list. I've also updated it to match FIgma header. Further the ActionBar has been refactored to now simply accept title and subTitle and ChatScreen creates and sends the appropriate strings. Screenshots:

![Screenshot_1666740074](https://user-images.githubusercontent.com/43901/197900324-2f114d12-a772-49e7-8215-a15c53821325.png)

![Screenshot_1666740077](https://user-images.githubusercontent.com/43901/197900347-a9e81cf9-d3c9-4cba-a5e9-51ef8d8a6a11.png)

2022-10-26 21:40 UTC, JoshuaLai commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/state/ParticipantsState.kt
> +    val participantsListVisible: Boolean,
Should the ParticipantState hold onto a value for whether or not the list is visible? 
This seems incorrect to me. Whether or not the participant view is visible is a view concept and has nothing to do with the Participants state. @ahammer  @iaulakh  thoughts?

2022-10-26 21:48 UTC, JoshuaLai commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/chat/components/ActionBarView.kt
> +                                )
Would it be more correct to dispatch a navigation action to go to the participant list instead?

2022-10-26 22:45 UTC, ahammer approved these changes, later dismissed

2022-10-27 15:34 UTC, JoshuaLai approved these changes

2022-10-27 15:41 UTC, iaulakh approved these changes

2022-10-27 16:23 UTC, merged