[Chat][Feature] Unread messages redux
Azure/communication-ui-library-android pull request #558
Opened 2022-11-03 15:44 UTC by ShaunaSong

## Purpose

* Add unread messages logic

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-11-03 22:21 UTC, iaulakh requested changes
show 0 new messages for a second when received new message, even if message is visible

it should be a popup on top of messages. now taking screen around:
![Screenshot 2022-11-03 at 3 20 13 PM](https://user-images.githubusercontent.com/73618019/199845417-35a428c2-3e70-482f-911b-ec7e834977f4.png)

2022-11-03 23:41 UTC, Mohtasim commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/viewmodel/ChatScreenViewModel.kt
> +        }
when lastReadId is empty, unreadMessageCount should be the full message size. 
Right now it will return 0.

2022-11-03 23:41 UTC, Mohtasim commented on azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/viewmodel/ChatScreenViewModel.kt
> +        }
Can we do like -
maxId = max(lastReadId, lastSendId)
unreadMessageCount = message.size - maxID

So we can avoid the for loop and optimize.

2022-11-04 00:32 UTC, ShaunaSong commented
> show 0 new messages for a second when received new message, even if message is visible
> 
> it should be a popup on top of messages. now taking screen around: ![Screenshot 2022-11-03 at 3 20 13 PM](https://user-images.githubusercontent.com/73618019/199845417-35a428c2-3e70-482f-911b-ec7e834977f4.png)

<img width="247" alt="Screen Shot 2022-11-03 at 5 30 21 PM" src="https://user-images.githubusercontent.com/93549644/199860151-0ee0a2d7-0858-4fa9-9bc5-90035bbc88bc.png">

2022-11-04 16:19 UTC, iaulakh approved these changes

2022-11-04 16:54 UTC, Mohtasim approved these changes

2022-11-04 16:56 UTC, merged