[Feature] Audio Device List UI Test
Azure/communication-ui-library-android pull request #60
Opened 2022-02-15 20:49 UTC by phileo99

## Purpose

* added UI Test cases for audio device list

## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

```
./gradlew clean cDAT
```

## What to Check
Verify that all UI tests still pass

2022-02-18 19:12 UTC, ahammer submitted a review, later dismissed

2022-02-22 00:16 UTC, iaulakh requested changes

2022-02-22 00:16 UTC, iaulakh commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeAudioDeviceListTest.kt
> +package com.azure.android.communication.ui.callingcompositedemoapp
file is missing copyright

2022-02-22 00:16 UTC, iaulakh commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/matchers/BottomCellViewHolderMatcher.kt
> +
file is missing copyright

2022-02-22 00:16 UTC, iaulakh commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
>  // Licensed under the MIT License.
copyright

2022-02-23 19:47 UTC, ahammer reviewed
I can approve, once copyright is added

2022-03-05 02:35 UTC, phileo99 commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeAudioDeviceListTest.kt
> +package com.azure.android.communication.ui.callingcompositedemoapp
fixed

2022-03-05 02:35 UTC, phileo99 commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/matchers/BottomCellViewHolderMatcher.kt
> +
fixed

2022-03-05 02:36 UTC, phileo99 commented on azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
>  // Licensed under the MIT License.
fixed

2022-03-05 03:01 UTC, phileo99 commented
@iaulakh @ahammer all issues resolved and all checks are green

2022-03-06 02:06 UTC, iaulakh approved these changes

2022-03-07 17:14 UTC, ShaunaSong approved these changes

2022-03-07 17:20 UTC, ahammer approved these changes

2022-03-07 17:21 UTC, lpeixin approved these changes

2022-03-07 17:32 UTC, merged