[Chat][Bug] Dark mode user name text fix
Azure/communication-ui-library-android pull request #676
Opened 2022-12-12 22:01 UTC by Mrayyan

## Purpose

Original bug was that dark mode colors were not applying at all during bug bash. Tested it now and it all works fine. This PR just changes the user's display name so it is visible and readable in dark mode.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-12-13 03:15 UTC, iaulakh approved these changes, later dismissed

2022-12-13 19:50 UTC, ShaunaSong approved these changes, later dismissed

2022-12-15 00:12 UTC, ahammer requested changes
I think this is fixed in another PR I made yesterday
https://github.com/Azure/communication-ui-library-android/pull/681

Confirm before merging

2022-12-15 19:51 UTC, Mrayyan commented
> I think this is fixed in another PR I made yesterday #681
> 
> Confirm before merging

@ahammer  Yes, your pr already fixed it. This PR also had a small fix for the "In this Chat (n)" text width in dark mode. I guess we can merge that.

<img width="418" alt="Screen Shot 2022-12-15 at 11 46 38 AM" src="https://user-images.githubusercontent.com/24381490/207953302-b3788ee9-5964-41ac-ab43-a6a5743292fa.png">

2022-12-20 17:24 UTC, ShaunaSong approved these changes

2023-01-03 17:56 UTC, ahammer approved these changes

2023-01-03 18:35 UTC, merged