[Feature] Added App Center Crash Logging
Azure/communication-ui-library-android pull request #89
Opened 2022-03-02 08:48 UTC by Mrayyan

## Purpose

Enabled AppCenter for crash logging in demo app only for release build. Verified with a test crash.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-03-02 22:07 UTC, pavelprystinka requested changes

2022-03-02 22:07 UTC, pavelprystinka commented on azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
> +                "8cb48e80-76ae-43f4-939a-ab6edd255af4",
We should not hardcode app id here.
Let's make it as a part of the build process. When assembling and app in the pipeline we can populate local properties. Also this way we will avoid posting crash logs happened while developing on the local machine.

2022-03-08 20:48 UTC, ShaunaSong approved these changes

2022-03-08 20:56 UTC, lpx1989 approved these changes

2022-03-08 21:14 UTC, pavelprystinka approved these changes

2022-03-08 21:17 UTC, merged