[Calling][Refactor] hide lobby admit buttons because of sdk 2.6.0 video issue
Azure/communication-ui-library-android pull request #940
Opened 2024-02-21 19:24 UTC by iaulakh

## Purpose

* [Calling][Refactor] hide lobby admit buttons because of sdk 2.6.0 video issue

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-02-21 20:18 UTC, ahammer requested changes
Please fix versions in build.gradle to keep the beta version up to date.

_beta is meant to be always pinned as far in the future as possible, please never downgrade it.

2024-02-21 20:18 UTC, ahammer commented on azure-communication-ui/build.gradle
> +            azure_calling_sdk_version_beta = '2.5.0'
Please keep _beta at the newest released version (or beta) always. 

The beta build uses API in 2.6.0-beta+ so this change will break the beta build features (access to getLogFiles()) that have compile time features implemented.

2024-02-21 20:39 UTC, ahammer approved these changes

2024-02-21 21:10 UTC, jamchengms approved these changes

2024-02-21 21:19 UTC, pavelprystinka commented on azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
> +//                } else if (accessibilityManager.isEnabled) {
It looks like you have commented out too much here. Are you sure you need to remove non-lobby case?

2024-02-21 21:21 UTC, pavelprystinka approved these changes

2024-02-22 00:26 UTC, jamchengms approved these changes

2024-02-22 01:05 UTC, merged