[Calling][Refactor] Update deploy apk pipeline
Azure/communication-ui-library-android pull request #978
Opened 2024-04-13 03:08 UTC by ShaunaSong

## Purpose

* Migrate deploy apk based on S360 requirement 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [ ] Public API changes
- [ ] Verified for cross-platform
- [ ] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Open...
* Click on...

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-04-13 18:25 UTC, pavelprystinka requested changes

2024-04-13 18:25 UTC, pavelprystinka commented on eng/pipelines/deployAPK.yml
> +name: $(date:yyyyMMdd)$(rev:.r) $(Build.BuildId)
Thanks @ShaunaSong  for migrating to yml.
I have updated existing pipeline yesterday to include pom file in the souces.jar file when building a package. 
Then new task created is "Put .pom file to the .aar file"

2024-04-13 18:38 UTC, pavelprystinka approved these changes

2024-04-15 15:07 UTC, iaulakh approved these changes

2024-04-15 21:00 UTC, merged